apiVersion: v1
kind: Service
metadata:
  labels:
    app: inboundgw
  name:  inboundgw-ext
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.169.50  
  ports:
    - port: 5001
  selector:
    app: inboundgw
---
apiVersion: v1
kind: Service
metadata:
  name: inboundgw
  labels:
    app: inboundgw
spec:
  ports:
  - port: 5001
    name: inboundgw
  clusterIP: None
  selector:
    app: inboundgw
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inboundgw
spec:
  podManagementPolicy: "Parallel"      
  selector:
    matchLabels:
      app: inboundgw
  serviceName: inboundgw
  replicas: 1 
  template:
    metadata:
      labels:
        app: inboundgw
    spec:
      containers:
        - name: inboundgw
          image: localhost:32000/inboundgw
          command:  ["/bin/bash", "-c","--", "/start.sh"]
          volumeMounts:
            - mountPath: "/myfixlogs"
              name: www
            - mountPath: /myetc
              name: inboundgw-config
      volumes:
        - name: inboundgw-config
          configMap:
            name: inboundgw-config
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: microk8s-hostpath #nfs-csi
      #microk8s-hostpath
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
