run:
  timeout: 10m
  skip-dirs:
    - gen
    - vendor

linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - unused
    - varcheck
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/quickfixgo/quickfix
  dupl:
    threshold: 400